### ISSUE TITLE
Question about htseq-count for SS3 and VASA-seq

### ISSUE THREAD

**Issue by biobenkj** [zonglab/snapTotal-seq#1]
Hello! Thank you so much for including all the code for reproducing analysis! I wanted to ask about treating the strandedness for Smart-seq3 and VASA-seq (plate). Were these treated as unstranded for gene detection counting? I assume so with the `-s no` but wanted to ask. Thanks!

**Comment by biobenkj** [comment]
just bumping this question up

**Comment by biobenkj** [comment]
another bump. thanks!

**Comment by ychniu** [comment]
> Hello! Thank you so much for including all the code for reproducing analysis! I wanted to ask about treating the strandedness for Smart-seq3 and VASA-seq (plate). Were these treated as unstranded for gene detection counting? I assume so with the `-s no` but wanted to ask. Thanks!

Hi Ben,

In order to achieve equal-footing comparison, we also treated them as unstranded for gene detection counting. 

Yichi

**Comment by biobenkj** [comment]
Thank you
